version: '2'
services:
  knotctl:
    build: .
    image: knot/knotctl
    container_name: knotctl
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
    ports:
      - '8080:8080'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/usr/local/bin/knot-control-source
      - /usr/local/bin/knot-control-source/node_modules
    environment:
      MONGODB_URI: 'mongodb://database/knot_fog'
  database:
    image: mongo
    ports:
      - "27017:27017"